services:
  # app
  app:
    build:
      context: .docker
      dockerfile: Dockerfile
    image: a20-admin-reports:latest
    container_name: app
    restart: unless-stopped
    tty: true
    ports:
      - 9070:9070
      - 5173:5173
    volumes:
      - ./:/var/www/html
      - ./.docker/php.ini:/etc/php/8.4/fpm/conf.d/99-php.ini
      - ./.docker/fpm-pool.conf:/usr/local/etc/php-fpm.conf
      - ~/.ssh:/home/laravel/.ssh
    depends_on:
      - db
      - redis
      - mail
      - minio
    networks:
      - default

  # Nginx
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html
      - ./.docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    mem_limit: 256m
    cpus: "0.25"
    networks:
      - default

  # Database
  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    ports:
      - ${DB_PORT:-3306}:3306
    environment:
      - MYSQL_ROOT_PASSWORD=laravel
      - MYSQL_DATABASE=${DB_DATABASE:-laravel}
      - MYSQL_USER=${DB_USERNAME:-laravel}
      - MYSQL_PASSWORD=${DB_PASSWORD:-laravel}
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - default

  # Redis
  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - ${REDIS_PORT:-6379}:6379
    volumes:
      - redis:/data
    networks:
      - default

  # Mail
  mail:
    image: axllent/mailpit:latest
    container_name: mail
    restart: unless-stopped
    ports:
      - ${MAIL_PORT:-1025}:1025
      - 8025:8025
    networks:
      - default

  # S3/R2
  minio:
    image: minio/minio:RELEASE.2024-01-29T03-56-32Z
    container_name: minio
    restart: unless-stopped
    ports:
      - 9000:9000
      - 8900:8900
    environment:
      - MINIO_ROOT_USER=${AWS_ACCESS_KEY_ID:-laravel}
      - MINIO_ROOT_PASSWORD=${AWS_SECRET_ACCESS_KEY:-password}
    volumes:
      - minio:/data
    command: minio server /data/minio --console-address ":8900"
    networks:
      - default

# Networks
networks:
  default:
    driver: bridge

# Volumes
volumes:
  mysql:
    driver: local
  minio:
    driver: local
  redis:
    driver: local
